### ISSUE TITLE
Search Input - Throws Warning in Console

### ISSUE THREAD

**Issue by nk-gears** [mjakal/react-async-table#2]
I am getting this error whenever i enable the search box. Is this a issue with integrating with hooks.

Warning: A component is changing a controlled input of type text to be uncontrolled. Input elements should not switch from controlled to uncontrolled (or vice versa). Decide between using a controlled or uncontrolled input element for the lifetime of the component. More info

**Comment by mjakal** [comment]
Currently I'm not using react hooks in my project, but query param must be tracked in your state. See the example below:

```
import React from 'react';

class Example extends React.Component {
  constructor(props) {
    super(props);

    this.state = { search: '' };

    this.onSearch = this.onSearch.bind(this);
  }

  
  onSearch(search) {
    this.setState({ search });
  }

  render() {
    const { search } = this.state;

    return (
        <ReactAsyncTable
            ...
            query={search}
            onSearch={this.onSearch}
            ...
        />
    );
  }
}

export default Example;
```
